version: '3.9'

networks:
  todo:
    driver: bridge

services:
  app:
    container_name: UserStore.API
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 80:80
    networks:
     - todo
    depends_on:
     - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "usersdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
     - todo

volumes:
  postgres-data: